### ISSUE TITLE
[FEA] Remove `FutureWarning`s from Python tests

### ISSUE THREAD

**Issue by bdice** [rapidsai/cudf#10363]
This is a meta-issue as part of #9999. Here, I catalog the current list of test files that raise a `FutureWarning`.

The use of a `FutureWarning` indicates a deprecated API, mostly from cudf or pandas. We should explicitly catch or filter out these warnings, depending on the circumstances. Eventually we will be able to run `pytest -W error::FutureWarning` to catch any deprecated APIs being called by our tests, which may conceal a regression in the user API.

- [x] `test_csv.py` #10362
- [x] `test_cuda_apply.py` #10402
- [ ] `test_dataframe.py`
- [x] `test_groupby.py`
- [x] `test_index.py`
- [x] `test_indexing.py` #12305
- [x] `test_joining.py` #12304
- [x] `test_multiindex.py` #12310
- [x] `test_numerical.py` #10402
- [x] `test_orc.py`
- [x] `test_parquet.py` (partial) #10416
- [x] `test_pickling.py` #10402
- [x] `test_rolling.py` #10405
- [x] `test_stats.py` #12293
- [x] `test_timedelta.py` #10418
- [x] `test_unaops.py` #10402
- [ ] Update tests to fail on `FutureWarning`: `pytest -W error::FutureWarning`

**Comment by bdice** [comment]
I traced down some unexpected behavior and it turns out to be an error in the Python docs. This comment explains what I found, for posterity/reference. cc: @galipremsagar

I tried to specify a warning filter `pytest -W error::FutureWarning:cudf.*` on the command line. This follows the guidelines for [how to specify warning filters](https://docs.python.org/3/library/warnings.html#describing-warning-filters) as `action:message:category:module:line`.

I expected that this would raise an error for any `FutureWarning` raised by the `cudf` module or its subpackages, by interpreting the `cudf.*` module string as a regular expression. However, we can't do this with `-W`, because the input strings for `message` and `module` are escaped and not interpreted as regular expressions when defined with `-W` or `PYTHONWARNINGS`. The docs indicate that the module string is always treated as a regular expression, but that is only true for `warnings.filterwarnings` and not the command line option `-W` or environment variable `PYTHONWARNINGS`. This problem in the docs was reported in https://bugs.python.org/issue42272 and fixed in https://github.com/python/cpython/pull/23172.

The workaround for this is to define this in our pytest configuration, `setup.cfg`, with the following:

```ini
[tool:pytest]
filterwarnings = error::FutureWarning:cudf.*
```

References:
- https://stackoverflow.com/questions/71112211/why-does-pythons-filterwarning-module-regex-not-work-as-expected
- https://stackoverflow.com/questions/40710094/how-to-suppress-py-test-internal-deprecation-warnings
