### ISSUE TITLE
[FEA] Supported chunked reading of ORC files

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#12228]
**Is your feature request related to a problem? Please describe.**
This is essentially the same thing as was done for parquet in https://github.com/rapidsai/cudf/pull/11867, except we would like to be able to parse ORC files.

**Describe the solution you'd like**
A new ORC parsing APIs that would let us read files that have really large stripes, and ideally have a best effort target size.

**Describe alternatives you've considered**
We don't have a lot of choices if the customer is in a situation where the stripe is too large, or has nested types in the stripe that would violate the size limitation for cudf::size_type.

**Additional context**
The parquet version looks to be working rather well.

```[tasklist]
### Tasks
- [x] Refactor ORC reader: https://github.com/rapidsai/cudf/pull/13396
- [ ] Implement ORC chunked reader: https://github.com/rapidsai/cudf/pull/15094
- [ ] JNI for ORC chunked reader: https://github.com/rapidsai/cudf/pull/15446
```

**Comment by ttnghia** [comment]
I've started to work on this. However, it will be beyond the 23.06 release.

**Comment by ttnghia** [comment]
The ORC chunked reader is implemented through an iterative refinement way. That involves several steps, one after another:
  1. Firstly, the ORC reader is refactored to extract the code into several submodules:
    *File preprocessing: Reads raw file data.
    *Chunking: To compute and store chunk information such as the beginning/end row of each chunk to read.
    * Common helper functions: To perform various functionalities such as creating an output column from the intermediate output buffer.
    * The main reader module: Coordinates between the submodules above.
  2. After refactoring, a simple chunked reader will be implemented that can support chunking at stripe-level. For this chunked reader, read output chunk will be read as a multiple of whole stripes.
  3. The chunk reader above is further refined into rowgroup-level chunk. In other words, each output chunk will be read from a multiple of consecutive rowgroups.
  4. Finally, each output chunk can be read with any arbitrary number of consecutive rows. This can support maximized granularity, but can be somewhat inefficient due to too much refined on the data. As such, this step is optional.
