### ISSUE TITLE
[FEA] Update IO benchmarks for consistency between formats

### ISSUE THREAD

**Issue by GregoryKimball** [rapidsai/cudf#12739]
**Is your feature request related to a problem? Please describe.**
- [ ] switch ORC reader to file data source #12678
- [ ] reduce multibyte split benchmarks #12675 
- [ ] include smaller file sizes to CSV benchmarks #12674 
- [ ] add benchmark coverage for parquet chunked reader. Perhaps modeled after [parquet_read_io_compression](https://github.com/rapidsai/cudf/blob/c20c8b42215e38bee207b49dad6e28ea04ccbd8c/cpp/benchmarks/io/parquet/parquet_reader_input.cpp#L143)
- [ ] migrate CSV writer to nvbench. Currently using gbench.
- [ ] add JSON writer benchmark. This benchmark could be modeled after CSV writer.
- [ ] add JSON reader benchmark with file data source ([NESTED_JSON](https://github.com/rapidsai/cudf/blob/branch-23.04/cpp/benchmarks/io/json/nested_json.cpp) only benchmarks parsing of device buffers). This benchmark could be modeled after CSV reader
- [ ] add multi-stream Parquet reader benchmark #12700 

**Additional context**
The initial set of topics came from a comparison of file read throughput across the supported formats in cuIO.
<img width="518" alt="image" src="https://user-images.githubusercontent.com/12725111/217667722-a5024218-61fb-410d-941d-9f9eed4f4c5a.png">
We are also preparing for a comparison of memory footprint across cuIO, especially with Zstd compression/decompression.
