### ISSUE TITLE
[FEA] Reference counting for memory owning objects in numba kernels

### ISSUE THREAD

**Issue by brandon-b-miller** [rapidsai/cudf#13053]
With the introduction of string datatypes inside user defined functions as well as the merging of the groupby JIT engine, there are now certain objects allowed within UDFs that are individually backed by a device allocation. This issue tracks the introduction of a CUDA version of the reference counting mechanism that powers numba's nopython mode for the CPU target. This mechanism will provide much more robust cleanup for the objects in question than the current approach which attempts to clean everything up in post-processing.

The below tasklist is a draft for now and may change as things are merged.

```[tasklist]
### Tasks
- [ ] https://github.com/rapidsai/cudf/pull/13060
- [ ] https://github.com/rapidsai/cudf/pull/13098
- [ ] https://github.com/rapidsai/cudf/pull/13125
- [ ] https://github.com/rapidsai/cudf/pull/13172
- [ ] https://github.com/rapidsai/cudf/pull/13181
```

**Comment by vyasr** [comment]
@brandon-b-miller I'm closing this issue as resolved by https://github.com/rapidsai/cudf/pull/18453, but please reopen if there's further work needed.
