### ISSUE TITLE
[FEA] Expose public stream-ordered C++ APIs

### ISSUE THREAD

**Issue by vyasr** [rapidsai/cudf#13744]
**Is your feature request related to a problem? Please describe.**
Currently most libcudf APIs operate implicitly on the default CUDA stream. As documented in #925, we would like to expose stream-ordered APIs publicly. Prior to doing so, we needed to do a great deal of work to ensure that libcudf's internals were properly stream-ordered. Among the important tasks here were removing implicit APIs that ran on a stream (see #11968) and implementing a strategy for verifying that streams are properly forwarded from APIs all the way down to the lowest level functions (see #11943). Now that all such work that we are aware of has been completed, libcudf should start exposing streams in public APIs. 

We originally considered adding stream support via a monolithic feature branch where APIs would be modified one at a time. From various discussions, however, we decided that the overhead of maintaining a feature branch would grow too large to be worthwhile, so we have instead decided to proceed by incrementally exposing streams in libcudf APIs over time. PRs adding new APIs should always include a stream in the public API. Existing APIs will be transitioned one header file at a time, with PRs going directly into the current main branch of cudf.

The purpose of this PR is to document progress on the task of transitioning existing headers, as well as to describe the process by which new stream-ordered APIs should be added.

**Describe the solution you'd like**
When adding stream support to an API, the stream parameter should be placed just before the mr parameter with a default value of `cudf::get_default_stream()`. A new test should be added that validates that the API properly forwards the stream to all CUDA calls, which can be done by following the instructions at the bottom of [libcudf's testing developer docs](https://docs.rapids.ai/api/libcudf/nightly/md_developer_guide_testing). 

To divide up the work, we consider public headers organized by directories (all relative to `cpp/include/cudf`). Devs may assign themselves a directory within which to own all headers and the public APIs contained therein.

### /cudf APIs

- [x] aggregation.hpp
- [x] ast/ #16452
- [x] binaryop.hpp #14187
- [x] column/
    - [x] column_device_view.hpp
    - [x] column_factories.hpp #14354
    - [x] column_view.hpp #14354
    - [x] column.hpp #14354
- [x] concatenate.hpp #13987 
- [x] contiguous_split.hpp
- [x] copying.hpp #13629
- [x] datetime.hpp #16775
- [x] dictionary/
    - [x] dictionary_column_view.hpp
    - [x] dictionary_factories.hpp #14115
    - [x] encode.hpp #14115
    - [x] search.hpp #14115
    - [x] update_keys.h #14115
- [x] filling.hpp #13990
- [x] fixed_point/
- [x] groupby.hpp #17324 
- [x] hashing/hashing.hpp #12090
- [x] interop.hpp #17397 
- [x] io/
    - [x] csv.hpp #14340
    - [x] json.hpp #14313
    - [x] parquet.hpp #14359
    - [x] orc.hpp #14350
    - [x] avro.hpp #17766  
- [x] join.hpp #16793
- [x] json/json.hpp
- [x] labeling/label_bins.h #14401
- [x] lists/
    - [x] contains.hpp #14248
    - [x] count_elements.hpp #14248
    - [x] count.hpp #14248
    - [x] extract.hpp #14272
    - [x] gather.hpp #14272
    - [x] reverse.hpp #14272
    - [x] sort.hpp #14272
- [X] merge.hpp #16124
- [x] null_mask.hpp #14263
- [x] partitioning.hpp #17213 
- [x] quantiles.hpp #17257 
- [x] reduction.hpp
- [x] replace.hpp #14010
- [x] reshape.hpp
- [x] rolling/
- [x] rolling.hpp
- [x] round.hpp #16925 
- [x] scalar/
    - [x] scalar.hpp #14354 
    - [x] scalar_device_view.cuh #14354 
     - [x] scalar_factories.hpp #14354 
- [x] search.hpp #14034
- [x] sorting.hpp #14146
- [x] stream_compaction.hpp
- [x] strings/
    - [x] attributes.hpp #17398 
    - [x] capitalize.hpp 
    - [x] case.hpp #14056
    - [x] combine.hpp #14281
    - [x] contains.hpp  #14280
    - [x] convert/ #14255
    - [x] extract.hpp
    - [x] find.hpp #14060
    - [x] find_multiple.hpp
    - [x] findall.hpp
    - [x] padding.hpp
    - [x] repeat_strings.hpp
    - [x] replace.hpp #14261
    - [x] replace_re.hpp #14261
    - [x] reverse.hpp
    - [x] slice.hpp
    - [x] split/ #13997 #14247
    - [x] string_view.cuh
    - [x] string_view.hpp
    - [x] strings_column_view.hpp
    - [x] strip.hpp
    - [x] translate.hpp
    - [x] utilities.hpp
    - [x] wrap.hpp
- [x] structs/
    - [x] struct_view.hpp
    - [x] structs_column_device_view.cuh
    - [x] structs_column_view.hpp
- [x] table/
    - [x] experimental/row_operators.cuh
    - [x] row_operators.cuh
    - [x] table.hpp
    - [x] table_device_view.cuh
    - [x] table_view.hpp
- [x] tdigest/
- [x] timezone.hpp #16775
- [x] transform.hpp
- [x] transpose.hpp #17294
- [x] unary.hpp #14342
- [x] wrappers/

### /nvtext APIs

- [x] byte_pair_encoding.hpp
- [x] edit_distance.hpp  #14456
- [x] generate_ngrams.hpp
- [x] jaccard.hpp
- [x] minhash.hpp
- [x] ngrams_tokenize.hpp  #14061
- [x] normalize.hpp
- [x] replace.hpp #14329
- [x] stemmer.hpp
- [x] subword_tokenize.hpp #17206 
- [x] tokenize.hpp #14317

**Additional context**
Before we began making public stream parameters, libcudf public APIs would be paired with detail APIs that are nearly identical except for having a required stream parameter. In some cases, though, the public API may not currently have a detail "mirror" function but instead call multiple detail APIs. In those cases we may need to make a case-by-case determination of whether a new detail function should also be added. Some discussion of whether we want this pattern to be present everywhere, and the reasons why we might want that, are discussed in #14276.

Public stream API readiness:
* revamp the entire test suite to use "test streams"
* create a few multi-stream benchmarks
* create a multi-stream example

**Comment by ZelboK** [comment]
Hi, 

I took a look yesterday and from what I saw the API for the column headers already expose the cuda stream. However I do not see a direct test for it.

**Comment by davidwendt** [comment]
> I took a look yesterday and from what I saw the API for the column headers already expose the cuda stream in the API. However I do not see a direct test for it.

The stream tests are located here: https://github.com/rapidsai/cudf/tree/branch-23.12/cpp/tests/streams
It is certainly possible we missed some tests. Which APIs did you find that are missing tests?

**Comment by vyasr** [comment]
There are a small set of APIs that had streams added before we made the current push for adding streams, largely in cases where cuspatial needed them. Those predate the stream testing.

**Comment by karthikeyann** [comment]
Source code of groupby should be updated to use stream from top level APIs.
https://github.com/rapidsai/cudf/pull/14354#discussion_r1384175665
Related https://github.com/rapidsai/cudf/issues/11463  https://github.com/rapidsai/cudf/issues/13737

**Comment by GregoryKimball** [comment]
Thanks @lamarrr for reworking this issue!

**Comment by shrshi** [comment]
As of 25.02, libcudf supports stream-ordered execution of its public APIs. 
Thank you to everyone who has contributed to this effort 🎉
