### ISSUE TITLE
[FEA] Port cuIO to `cudf::column` types

### ISSUE THREAD

**Issue by j-ieong** [rapidsai/cudf#2954]
**Is your feature request related to a problem? Please describe.**
This issue tracks the effort for moving cuIO (readers, writers, tests) to using the new column design and associated infrastructure.

**Describe the solution you'd like**
Currently, cuIO uses wrappers around the C-style `gdf_column` to aid in storing/accessing column metadata and allocating/deallocating memory. We should be able to get rid of the custom C++ wrappers and directly use the `cudf::column` and `cudf::table`.

*Prerequisites*:
- [x] Require new column code #2207.
- [x] Require string support  #2811 
- [x] Require different timestamp column types #2918 
- [ ] Require column name metadata in either column or table
- [ ] Detail how to hand-off to Cython / Python

**Describe alternatives you've considered**
We may or may not need some sort of temporary wrapper or custom column class still within cuIO to temporary hold column metadata that's format-specific, for delayed column creation to save memory or other usage. The returned columns will be `cudf::column` and `cudf:;table` though.

**Additional context**
See other porting efforts for `libcudf`.

**Comment by mjsamoht** [comment]
Moving to 0.12 for remaining tasks.

**Comment by mjsamoht** [comment]
Closing this issue.  Remaining work will be tracked in #3521 and #3522.
