### ISSUE TITLE
Update GitHub templates in /.github

### ISSUE THREAD

**Issue by mike-wendt** [rapidsai/cudf#300]
### TODO

- [x] Rename pygdf to cudf
- [x] Give guidance and standards on PRs that require C and Python code changes in the same PR
- [x] Update any contact information mentioned in the templates
