### ISSUE TITLE
[FEA] Fixed-point Decimal type support

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#3556]
**Is your feature request related to a problem? Please describe.**
cuDF should support fixed-point decimal types.

**Describe the solution you'd like**
Add a new `DECIMAL` type for `column`s.

The scale information will be stored per-column in the `data_type`.

Also requires a new `scaled_integer` type for encapsulating an integral value and a scale factor that provides arithmetic operators to allow operating on the fixed point values. E.g.,
```c++
template <typename Rep>
class scaled_integer{
   // Note that the scale must be runtime info
   scaled_integer(Rep value, int32_t scale);
};
```

While Arrow only supports 128 bit fixed-point decimals, this design will allow us to have 32bit, 64bit, etc.

**Describe alternatives you've considered**
The `scaled_integer` type from [CNL](https://github.com/johnmcfarlane/cnl) won't work because it requires the scale information to be compile time info.

**Additional context**
In order to support Decimal types with 128 bits of precision (like Arrow), we'll also need a 128 bit integer type.

#### Major PRS:
* [x] 1. Add `fixed_point` type (https://github.com/rapidsai/cudf/pull/3782)
* [x] 2. Initial `fixed_point` Column Support (https://github.com/rapidsai/cudf/pull/5704)
   * [x] `sort` / `gather`
   * [x] `scatter`  
   * [x] `replace`
   * [x] `upper_bound` / `lower_bound`
   * [x] `interleave`
   * [x] `concatenate`
   * [x] adding type `decimal32` and `decimal64` to relevant type lists
* [x] 3. Move `fixed_point::scale` to `data_type` (https://github.com/rapidsai/cudf/pull/5861)
   * [x]  Add `scale` into `data_type` 
   * [x]  Customize allocation factory functions (to only allocate for underlying value)
   * [x]  Specialize algorithms to that don't need to operate on full `fixed_point` type (i.e sort)
#### Minor PRs:
* [x] Enable more unit tests to work with `FixedWidthTypes` (instead of `FixedWidthTypesWithoutFixedPoint`) (https://github.com/rapidsai/cudf/pull/5817)
* [x] Enable `fixed_point` binary operations (https://github.com/rapidsai/cudf/pull/6528)
   * [x] Add `cudf::binary_operation` `NULL_MIN`, `NULL_MAX` & `NULL_EQUALS` for `decimal32` and `decimal64` (https://github.com/rapidsai/cudf/pull/7119)
* [x] Implement `cudf::round` `decimal32` & `decimal64` (`HALF_UP` and `HALF_EVEN`) (https://github.com/rapidsai/cudf/pull/6685)
* [x] Casting to/from floats, ints and decimal with other precision/accuracy
   * [x] Implement `cudf::cast` for `decimal32/64` to/from integer and floating point (https://github.com/rapidsai/cudf/pull/6711)
   * [x] Implement `cudf::cast` for `decimal32/64` to/from different scale (https://github.com/rapidsai/cudf/pull/6729)
* [x] Unary operators (abs, ceil, floor) (https://github.com/rapidsai/cudf/pull/6777)
* [ ] Unary operators MOD, PMOD and TRUE_DIV #7132 
   * [x] Support for `TRUE_DIV` (https://github.com/rapidsai/cudf/pull/7198)
   * [ ] Support for `(P)MOD`
* [ ] Aggregation operators
   * [x] `cudf::reduce` : `MIN`, `MAX`, `SUM`, `PRODUCT`, `NUNIQUE` (https://github.com/rapidsai/cudf/pull/6814)
   * [x] `cudf::reduce` : others (https://github.com/rapidsai/cudf/pull/6980)
   * [x] `cudf::scan` (https://github.com/rapidsai/cudf/pull/7063) 
   * [x] `cudf::groupby`
      * [x] Implement `cudf::group_by` (sort) for `decimal32` and `decimal64` (https://github.com/rapidsai/cudf/pull/7169)
      * [x] Implement `cudf::group_by` (hash) for `decimal32` and `decimal64` (https://github.com/rapidsai/cudf/pull/7190)
   * [x] `cudf::rolling_window` (https://github.com/rapidsai/cudf/pull/7037)
      * [x] `cudf::rolling_window` `ROW_NUMBER` support for `decimal32` and `decimal64` (https://github.com/rapidsai/cudf/pull/7061)
      * [x] `cudf::rolling_window` `SUM` support for `decimal32` and `decimal64` (https://github.com/rapidsai/cudf/pull/7147)
   * [ ] `cudf::grouped_rolling_window`
* [x] Support for `cudf::copy_range` algorithm (https://github.com/rapidsai/cudf/pull/6843)
* [x] Support for `cudf::clamp` algorithm (https://github.com/rapidsai/cudf/pull/6792)
* [x] Support for `cudf::detail::copy_if` / `cudf::apply_boolean_mask` (https://github.com/rapidsai/cudf/pull/6805)
* [x] Support for `cudf::copy_if_else` algorithm (https://github.com/rapidsai/cudf/pull/6845)
* [x] Add `scale` and `value` methods to `fixed_point` (https://github.com/rapidsai/cudf/pull/7109)
* [x] to_arrow / from_arrow #7116 
* [x] Add null mask `fixed_point_column_wrapper` constructors (https://github.com/rapidsai/cudf/pull/6951)
* [x] Make `cudf::round` for `fixed_point` when `scale = -decimal_places` a no-op (https://github.com/rapidsai/cudf/pull/6975) 
* [x] Adding unit tests for `fixed_point` with extremely large `scale`s (https://github.com/rapidsai/cudf/pull/7178)
* [x] Casting decimal<-->string #7285

**Comment by codereport** [comment]
Summarising some of the design choices that were made offline with @jrhemstad and @harrism:

- Radix type should be a compile time variable
- Radix type should be programmed generically, but cuDF is mostly concerned with base 10
- Constructors should support `integer` and `float` to start
- Constructors shouldn't allow implicit conversions (mark `explicit`)
- Arithmetic operators should only support `scaled_integer` types
- Want to support exponent types with different values for arithmetic operations unless it proves to be too difficult
- Use arrow for a reference: https://arrow.apache.org/docs/cpp/classarrow_1_1_decimal128.html

Updated class might look something like:
```cpp
using scale_type = int32_t;

// Rep = representative type
template <typename Rep, typename Radix>
class scaled_integer {
    template <typename T,
              typename std::enable_if_t<std::is_same<T, float>::value>* = nullptr>
    scaled_integer(T value, scale_type scale) {
        // implementation for int
    }

    template <typename T,
              typename std::enable_if_t<std::is_same<T, int>::value>* = nullptr>
    scaled_integer(T value, scale_type scale) {
        // implementation for float
    }
};
```
and then:
```cpp
using decimal32 = scaled_integer<int32_t, 10>;
```

**Comment by harrism** [comment]
Do you need the SFINAE shown here, or can you just specialize the template constructors (since the specifializations are for specific single types and they are not partial specializations)?

**Comment by jrhemstad** [comment]
> Do you need the SFINAE shown here, or can you just specialize the template constructors (since the specifializations are for specific single types and they are not partial specializations)?

Yeah, if you're only interested in `int/float` then just use overloads:
```c++
   scaled_integer(int value, scale_type scale) {
        // implementation for int
    }

    scaled_integer(float value, scale_type scale) {
        // implementation for float
    }
```
That would require 6 overloads (int8,16,32,64,float32,64).

I'd do SFINAE on traits like `is_integer/is_floating_point`

**Comment by kkraus14** [comment]
Looks like the only thing missing here is the `mod` / `pmod` operators and the `cudf::grouped_rolling_window` support. We already have a separate issue for the `mod` / `pmod` operators, so I think we should raise an issue for `cudf::grouped_rolling_window` and then we can close this out and follow up with any gaps in subsequent issues.

**Comment by kkraus14** [comment]
Closing as I've opened #8161 for tracking `cudf::grouped_rolling_window` libcudf support.
