### ISSUE TITLE
[FEA] Support dask-cudf

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#557]
This meta-issue tracks active needs for dask-cudf on the cudf API

- Core
    - [x] Thread Safety https://github.com/rapidsai/cudf/issues/528
    - [ ] Dask-CUDF needs CI: https://github.com/rapidsai/dask-cudf/issues/49
- Repartition
    - [x] Support comparison operations on Index objects https://github.com/rapidsai/cudf/issues/556
    - [x] Support comparison against Pandas TimeStamps https://github.com/rapidsai/cudf/issues/553
    - [x] Support iloc on rows: https://github.com/rapidsai/cudf/issues/606
-  Groupby-Aggregations
    - [ ] Support Pandas MultiIndex columns in groupby-aggregations: https://github.com/rapidsai/cudf/issues/483
- I/O
    - [x] Support byte ranges in read_csv: https://github.com/rapidsai/cudf/issues/568 (either this or parquet would be useful short-term)
    - [x] Support Parquet reading: https://github.com/rapidsai/cudf/issues/601 (either this or read_csv ranges would be useful short-term)
    - [x] read_csv fails intermittently: https://github.com/rapidsai/cudf/issues/625

**Comment by kkraus14** [comment]
Assigning myself to track and update issue as progress is made.

**Comment by kkraus14** [comment]
Given everything is in motion I'm going to close this to track the individual issues.
