### ISSUE TITLE
[FEA] Java bindings for fixed-point Decimal type

### ISSUE THREAD

**Issue by sperlingxx** [rapidsai/cudf#6515]
**Is your feature request related to a problem? Please describe.**
cuDF Java API should be able to leverage new cuDF feature, [fixed-point decimal type](https://github.com/rapidsai/cudf/issues/3556), in order to support decimal type in spark-rapids plugin ([issue link](https://github.com/NVIDIA/spark-rapids/issues/42)). 

**Describe the solution you'd like**
Initial Tasks
- [x] Add class DataType, and add Decimal32/64 into DType collection (#6514)
  - [x] Add class NativeDataType (which manages the handle of native data_type class)
  - [x] Package-level adaption for `Dtype -> DataType` transformation (check all references of DType)
  - [x] Scalar (scalar JNI, scalar building functions for decimalType)

Other Tasks
- [x] ColumnVectors (#6609)
- [x] BinaryOperations with decimal data
- [x] JCudfSerialization
- [x] Schema
- [x] TestUtils for decimal types

**Additional context**
Native Prerequisites
- [x] (__merged__) Move fixed_point::scale to data_type (#5861)
- [x] (__merged__) Enable `fixed_point` binary operations (#6528 #6544)
- [x] (__merged__) Read/write parquet/orc with fixed-point decimal data (#6969 )
- [x] (__merged__) Type casting between fixed-point decimal and other numeric types (#6486)
- [x] Support HALF_UP and HALF_EVEN rounding to a set number of decimal places (https://github.com/rapidsai/cudf/issues/3790)
- [x] Unary operators for fixed-point decimals
- [x] Aggregation operators for fixed-point decimals

**Comment by kkraus14** [comment]
Pushing this to 0.18

**Comment by revans2** [comment]
@sperlingxx how much is left for this to be done? I think it is almost all complete

**Comment by sperlingxx** [comment]
> @sperlingxx how much is left for this to be done? I think it is almost all complete

Yes, it is almost complete except some cuDF native tasks. Shall we close this issue?

**Comment by beckernick** [comment]
Are the outstanding tasks mentioned in this issue covered by any other issues? If so, perhaps this can be closed.

**Comment by harrism** [comment]
@sameerz @sperlingxx can you respond to @beckernick 's question above?

**Comment by sameerz** [comment]
The ORC read / write for decimal in cuio is done in per https://github.com/rapidsai/cudf/issues/7126 and can be followed up on with the JNI binding work.  We need to create issues (if we do not already have them) for unary operators for fixed-point decimals and aggregation operators for fixed-point decimals. 

The RAPIDS Spark tasks related to this issue are tracked in https://github.com/NVIDIA/spark-rapids/issues/42
