### ISSUE TITLE
[FEA] Improve organization of AST code

### ISSUE THREAD

**Issue by vyasr** [rapidsai/cudf#8145]
Now that conditional joins have been merged, I'll use this PR as a checklist for the various improvements that we'd like to make to the code base:
- [x] Remove dependence of conditional joins on hash joins: #8815
- [x] Separate AST internals from compute_column implementation: #8900, #8930 
- [x] Hide all AST details from the user, expose only expression construction: #8900, #8930 
- [x] Move `compute_column` API to a user-facing namespace outside of ast: #8957
- [x] Expose null handling on a per-operator basis rather than a single option for null equality comparisons #9096
- [x] **WONTFIX**: ~~Upgrade arity dispatching: either infer arity directly from the operator functions, or encode this data at a higher level and remove all the extra functors~~ The fact that `operator()` is itself templated for the various `operator_functor` specializations makes this impossible without some very ugly workarounds that hurt readability and are in any case not robust to all possible cases.
- [x] **WONTFIX**: ~~Improve `device_data_reference`/`expression_result` structure.~~ I've experimented with changing `device_data_reference` from a POD struct into something with methods to encapsulate reading and writing logic and unify the `expression_result` class, but the amount of divergence between different reference types and output types means that the extra logic involved in dispatching appropriately obviates any real gains, at least with the current architecture.
- [x] Accept more parameters (including expressions) via const ref rather than by value. #9045 
- [x] Expose node class publicly so that client code can build up the list of nodes irrespective of type. #9045 
- [x] Add virtual destructor for nodes so that all node pointers are destructible. #9045 

This issue was originally created in from https://github.com/rapidsai/cudf/pull/7418#issuecomment-822838868, but has since been heavily edited to reflect the updated task list.

**Comment by harrism** [comment]
@vyasr how did you create an issue without choosing the type? Usually the system auto-populates some labels...

**Comment by vyasr** [comment]
You can create an issue from a comment on another PR or Issue by clicking on the three dots on the right and selecting "Reference in a new issue" (see the picture below). Issues created this way get the "_Originally posted by..._" note at the end of the issue. I'm surprised that it bypasses the auto-labeling though...

<img width="935" alt="image" src="https://user-images.githubusercontent.com/1538165/116943282-196a5380-ac28-11eb-8811-316ad1fc4d01.png">

**Comment by vyasr** [comment]
Now that conditional joins have been merged, I'll use this PR as a checklist for the various improvements that we'd like to make to the code base:
- [ ] Remove dependence of conditional joins on hash joins
- [ ] Hide all AST details from the user, expose only expression construction
- [ ] Move `compute_column` API to a user-facing namespace outside of ast
- [ ] Expose null handling on a per-operator basis rather than a single option for null equality comparisons
- [ ] Upgrade arity dispatching: either infer arity directly from the operator functions, or encode this data at a higher level and remove all the extra functors
- [ ] Improve `device_data_reference`/`expression_result` structure

**Comment by harrism** [comment]
>  I'll use this PR as a checklist

This is an issue. :)  But in general checklists should go into the opening comment (the issue description). This way the checklist counter shows up in github's other interfaces (e.g. project boards).
