### ISSUE TITLE
[Story] Reorganize and improve cudf classic tests

### ISSUE THREAD

**Issue by vyasr** [rapidsai/cudf#9999]
**Note for developers**
This is a meta-issue aiming to categorize a wide range of issues. Developers who want to tackle a specific item from the checklist below should create a new issue for just that item, self-assign that issue, and then link it to the checklist above.

**Is your feature request related to a problem? Please describe.**
There are currently a number of different problems that make it difficult to find, add, or run tests.
- Tests are partially and inconsistently organized by functionality, data types, and parametrizations, so it's not clear which file tests of a specific function might be in. The partial organization by dtype is particularly confusing because it means that in some files we test a single function across many dtypes, whereas in other files we test many functions for a single dtype.
- Test files are too large and contain too many tests.
- There are currently many tests that raise warnings as well as many xfailed tests that actually xpass.
- Tests are currently slow to run because we rely on excessive parametrization and we test many private APIs. Additionally, cuIO tests are especially slow because the corresponding libcudf APIs are difficult to test, so a greater burden is placed on the Python APIs to capture a wider range of issues.

**Describe the solution you'd like**
These are tasks that we propose to undertake to address the various issues discussed above:

- [x] See #7386. Change pytest to run fail on xpasses by specifying the `strict` parameter. [Here are the relevant pytest docs](https://docs.pytest.org/en/latest/how-to/skipping.html#strict-parameter). 
- [x] Make pytest fail when it encounters warnings. We can accomplish this by setting in the appropriate config file (probably setup.cfg). (Done in #12468)
  - [x] #10363
  - [x] Remove other warnings from Python tests (this was done across a large number of PRs)
- [ ] Reorganize test files to match the groupings in our API documentation. See also #4730
- [ ] Reorganize tests into classes that reflect the actual class hierarchies. For example, tests that should be performed for Series and DataFrame objects can go into a `test_indexed_frame.py` file.
- [ ] Reduce excessive parametrization. Many individual tests are actually run hundreds or even thousands of times because we construct a matrix of parameters. In many cases those parametrizations aren't actually testing anything useful, for instance when a test is parametrized by input size. In cases where we're worried about how the underlying libcudf algorithm behaves when block sizes are exceeded, for instance, we should push those tests down to C++. Python tests should favor fewer parameters and in some cases more specialized tests to handle specific edge cases.
- [ ] Where appropriate, we should replace parametrization with fixtures. Fixtures will be typically evaluated lazily unlike parameters, which are materialized when the decorated functions are defined, so changing this should improve collection time and reduce the frequency with which we see failures during collection. Additionally, it makes it easier to debug failing tests when breakpoints are placed in the code; we don't want to hit breakpoints during collection. #2530 is related to this and may be resolved by addressing this task, but it's not quite as broad.
- [ ] Remove tests of private functions/classes. If those functions/classes have corresponding public APIs, we need to make sure that those APIs are tested. If they are, then the tests of private code may be removed, otherwise those tests should be rewritten in terms of the corresponding public APIs.
- [x] Stop using pd._testing (#6435)
- [x] #10001
- [ ] Implement standard fixtures or use a similar approach to ensure consistent dtype coverage in tests. As part of this, decide what constitutes sufficient dtype coverage

**Comment by bdice** [comment]
I have started looking into `xfail_strict=true` in PR #9998. That will require some significant work to analyze all the `xfail` tests that pass (1956 tests failed with `xfail_strict=true`, and most of those are xpassed strict failures). I am going to prioritize solving locally failing tests like #7314 and reduce the number of warnings in the pytest log first, before going back to #9998.

**Comment by vyasr** [comment]
@mroeschke I've assigned this issue to you since it is a superset of #10001. We can definitely work on it in chunks, though, and none of it is urgent (although obviously reducing CI turnaround time is pretty much always a win).

**Comment by vyasr** [comment]
There is a bash script in #15652 for detecting undesirable parametrizations that could be helpful. What would be even more powerful, but possibly harder to implement just right, is some sort of monkeypatched wrapper for pytest.mark.parametrize that catches the cases that we don't want.

**Comment by mroeschke** [comment]
Noting as of ~ [`530307b`](https://github.com/rapidsai/cudf/commit/530307bf7bfb32e3eb51ab550a6824417b4ce9d7), the CUDA 12.9.1, Python 3.13, latest dependency job runs the cudf classic tests in 460.64s (0:07:40) with pytest-xdist (8 workers)

**Comment by mroeschke** [comment]
Comparing to the same job referenced in https://github.com/rapidsai/cudf/issues/9999#issuecomment-3099416110 (CUDA 12.9.1, Python 3.13, latest dependency job), as of https://github.com/rapidsai/cudf/pull/19958 (which will likely be merged), the cudf classic jobs run in in 269.99s (0:04:29) with with pytest-xdist (8 workers), about a 1.7x speedup! There might have also been improvements in the runtime of the library as well that helped contribute to the speedup of running the test suite.

I think this is a good stopping point for this issue so going to close this issue. We can open individual issues for further improvements to the test suite
